parameters:
    env(MYSQL_HOST): ''
    env(MYSQL_DATABASE): ''
    env(MYSQL_USER): ''
    env(MYSQL_PASSWORD): ''
    env(MYSQL_ROOT_PASSWORD): ''

doctrine:
    dbal:
        host: '%env(resolve:MYSQL_HOST)%'
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci