version: '3.1'

services:

  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    container_name: ${PROJECT_NAME}_adminer
    image: adminer
    ports:
      - 8080:8080
      
  php:
    container_name: ${PROJECT_NAME}_php
    image: php:7.2-fpm

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx
    volumes:
      - ./automation/docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public:/var/www/html/public
    ports:
      - 8081:80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"